{inputs, ...}: {
  imports =
    [(import ./waybar)]
    ++ [(import ./firefox)]
    ++ [(import ./vscode)]
    ++ [(import ./hyprland)]
    ++ [(import ./gaming)]
    ++ [(import ./git)]
    ++ [(import ./btop)]
    ++ [(import ./bat)]
    ++ [(import ./cava)]
    ++ [(import ./kitty)]
    ++ [(import ./aseprite)]
    ++ [(import ./audacious)]
    # ++ [(import ./discord)]
    ++ [(import ./swaylock)]
    ++ [(import ./wofi)]
    ++ [(import ./zsh)]
    ++ [(import ./gtk)]
    ++ [(import ./mako)]
    ++ [(import ./scripts)]
    ++ [(import ./neofetch)]
    ++ [(import ./starship)]
    ++ [(import ./wlogout)]
    ++ [(import ./nvim)]
    ++ [(import ./package)];
}
